class_name TileLoader
extends RefCounted

## Builds the shared flood-city overworld TileSet (assets/tiles/
## flood_tileset.png, generated by tools/gen_tiles.py) on demand. Tile
## order/names must match TILE_ORDER in that script.
##
## Districts opt into tile rendering by having a non-empty `terrain` array
## (see DistrictData); overworld.gd falls back to its plain colored-grid
## rendering for any district without one, same fallback pattern as
## SpriteLoader for character/monster art.

const TILESET_PATH := "res://assets/tiles/flood_tileset.png"
const TILE_SIZE := 40
const TILE_NAMES := ["shallow_water", "deep_water", "wet_pavement", "rubble"]

static func has_tileset() -> bool:
	return ResourceLoader.exists(TILESET_PATH)

static func build_tileset() -> TileSet:
	var tile_set := TileSet.new()
	tile_set.tile_size = Vector2i(TILE_SIZE, TILE_SIZE)

	var source := TileSetAtlasSource.new()
	source.texture = load(TILESET_PATH)
	source.texture_region_size = Vector2i(TILE_SIZE, TILE_SIZE)
	for i in TILE_NAMES.size():
		source.create_tile(Vector2i(i, 0))

	tile_set.add_source(source, 0)
	return tile_set

static func atlas_coords_for(tile_name: String) -> Vector2i:
	var idx: int = TILE_NAMES.find(tile_name)
	if idx == -1:
		idx = 0
	return Vector2i(idx, 0)
